# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

### Import NumPy as its abbreviation 'np'

In [1]:
import numpy as np

### Create a 1-dimensional NumPy array using np.array() 

In [2]:
arr1D = np.array([1,2,3,4])
arr1D

array([1, 2, 3, 4])

### Create a 2-dimensional NumPy array using np.array() 

In [3]:
arr2D = np.array([[1,2,3,4],[5,6,7,8]])
arr2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type) 

In [4]:
arr1D.shape, arr1D.ndim, arr1D.dtype, arr1D.size, type(arr1D)

((4,), 1, dtype('int32'), 4, numpy.ndarray)

### Attributes of 2-dimensional array

In [5]:
arr2D.shape, arr2D.ndim, arr2D.dtype, arr2D.size, type(arr2D)

((2, 4), 2, dtype('int32'), 8, numpy.ndarray)

### Create an array of shape (5, 5) with only ones 

In [6]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Create an array of shape (3, 3, 5) with only zeros

In [7]:
zeros = np.zeros((3, 3, 5))
zeros

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### Create a random array with numbers between 0 and 10 of size (7, 2)

In [8]:
randomArray = np.random.randint(10, size=(7, 2))
randomArray

array([[5, 0],
       [8, 2],
       [2, 5],
       [6, 9],
       [0, 2],
       [7, 1],
       [2, 8]])

### Create a random array of floats between 0 & 1 of shape (3, 5)

In [9]:
random_Array = np.random.random((3, 5))
random_Array

array([[0.38060532, 0.78232252, 0.90295875, 0.89669606, 0.55575429],
       [0.33120094, 0.22490268, 0.5606637 , 0.38439909, 0.71570181],
       [0.33532669, 0.28305258, 0.49773309, 0.08443404, 0.22185347]])

### Create an array of normally distributed random numbers

In [10]:
NormalDis = np.random.normal(0.5,5,15)
NormalDis

array([ 1.78221296, -2.59973459,  2.56880323, -6.38736872,  0.04466564,
       -0.69818608, -4.92178991, -3.04140132,  8.996105  ,  8.74557973,
       -1.03499321,  7.04140789, -1.22512534, 12.39728366, -2.60095513])

### Set the random seed to 42
### Create a random array of numbers between 0 & 10 of size (4, 6)

In [11]:
np.random.seed(42)
RandArray = np.random.randint(10, size=(4, 6))
RandArray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

### Copy the code from the cell above and run it again

In [12]:
np.random.seed(42)
RandArray = np.random.randint(10, size=(4, 6))
RandArray

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

### Find the 0'th index of the latest array you created

In [13]:
RandArray[0]

array([6, 3, 7, 4, 6, 9])

### Get the first 2 rows of latest array you created

In [14]:
RandArray[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

### Get the first 2 values of the first 2 rows of the latest array

In [15]:
RandArray[:2,:2]

array([[6, 3],
       [2, 6]])

### Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables

In [16]:
Array = np.random.randint(10, size=(3,5))
ones = np.ones((3,5))
Array, ones

(array([[8, 0, 9, 2, 6],
        [3, 8, 2, 4, 2],
        [6, 4, 8, 6, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

### Add the two arrays together

In [17]:
Array + ones

array([[ 9.,  1., 10.,  3.,  7.],
       [ 4.,  9.,  3.,  5.,  3.],
       [ 7.,  5.,  9.,  7.,  2.]])

### Create another array of ones of shape (5, 3)

In [18]:
Ones = np.ones((5,3))
Ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Try add the array of ones and the other most recent array together # You can anticipate an error

In [19]:
Array + Ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

### Do the same operation you just did but this time with a transpose on one array

In [20]:
Array.T + Ones

array([[ 9.,  4.,  7.],
       [ 1.,  9.,  5.],
       [10.,  3.,  9.],
       [ 3.,  5.,  7.],
       [ 7.,  3.,  2.]])

### Take the latest array to the power of 2 using the python way

In [21]:
Array ** 2

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]], dtype=int32)

### Do the same thing with numpy way

In [22]:
np.power(Array, 2)

array([[64,  0, 81,  4, 36],
       [ 9, 64,  4, 16,  4],
       [36, 16, 64, 36,  1]], dtype=int32)

### Find the mean, min, max, standard deviation, variance of the latest array using np.mean()

In [23]:
np.mean(Array), np.max(Array), np.min(Array), np.std(Array), np.var(Array)

(4.6, 9, 0, 2.8000000000000003, 7.840000000000002)

### Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)

In [24]:
a1 = np.random.randint(10, size = (3,3))
a2 = np.random.randint(10, size = (3,2))
a1 , a2

(array([[3, 8, 1],
        [9, 8, 9],
        [4, 1, 3]]),
 array([[6, 7],
        [2, 0],
        [3, 1]]))

### Perform a dot product on the two newest arrays you created

In [25]:
np.dot(a1, a2)

array([[37, 22],
       [97, 72],
       [35, 31]])

### Create two arrays of random integers between 0 to 10 both of size (4, 3)

In [26]:
b1 = np.random.randint(10, size = (4,3))
b2 = np.random.randint(10, size = (4,3))
b1, b2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1],
        [9, 1, 9]]),
 array([[3, 7, 6],
        [8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]))

### Perform a hadamard product on the two newest arrays you created

In [27]:
b1 * b2

array([[21, 21,  6],
       [40, 35, 36],
       [ 3, 20,  7],
       [81,  8, 72]])

### Perform a dot product on the two newest arrays you created # Error anticipated

In [28]:
np.dot(b1, b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

### Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both

In [29]:
np.dot(b1, b2.T)

array([[ 48,  81,  26,  95],
       [104, 111,  88, 157],
       [ 50,  63,  30,  75],
       [ 88, 115,  76, 161]])

### Create two arrays of random integers between 0 & 10 of the same shape and save them to variables

In [30]:
a1 = np.random.randint(10, size = (3,5))
a2 = np.random.randint(10, size = (3,5))

### Compare the two arrays with '>', '<=' and '=='

In [31]:
 a1  

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [32]:
a2

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [33]:
a1 > a2

array([[False,  True, False, False,  True],
       [False, False,  True,  True, False],
       [ True, False, False, False, False]])

In [34]:
a1 <= a2

array([[ True, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [35]:
a1 == a2

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

### Sort one of the arrays you just created in ascending order

In [36]:
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [37]:
np.sort(a1)

array([[0, 6, 7, 8, 8],
       [0, 0, 2, 7, 7],
       [0, 2, 2, 4, 7]])

### Sort the indexes of one of the arrays you just created

In [38]:
np.argsort(a1)

array([[0, 2, 4, 1, 3],
       [0, 4, 3, 1, 2],
       [3, 1, 2, 4, 0]], dtype=int64)

### Find the index with the maximum value in one of the arrays you've created

In [40]:
arr1D

array([1, 2, 3, 4])

In [41]:
np.argmax(arr1D)

3

### Create an array with 10 evenly spaced numbers between 1 and 100

In [42]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

### Find the indexes with the maximum values down the verticial axis of one of the arrays you created

In [43]:
a1

array([[0, 8, 6, 8, 7],
       [0, 7, 7, 2, 0],
       [7, 2, 2, 0, 4]])

In [44]:
np.argmax(a1,axis=0)

array([2, 0, 1, 0, 0], dtype=int64)

### Find the indexes with the minimum values across the horizontal axis of one of the arrays you created

In [45]:
a2

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

In [46]:
np.argmin(a2,axis=1)

array([1, 3, 3], dtype=int64)